version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 10
    versioning-strategy: lockfile-only
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 10
