editor:
  - apps/client-web/**/DocumentPage.*
  - apps/client-web/**/DocumentContentPage.*
  - packages/brickdoc-editor/**
  - packages/brickdoc-formula/**
  - tools/e2e-testing/tests/document/editor/**
document:
  - apps/client-web/**/DocumentTitle.*
  - apps/client-web/**/DocumentIcon/**
  - apps/client-web/**/DocumentCover/**
  - packages/brickdoc-uploader/**
  - tools/e2e-testing/tests/document/header/**
page:
  - apps/client-web/**/NewPage/**
  - apps/client-web/**/DocumentContentPage.*
  - apps/client-web/**/PageMenu/**
  - apps/client-web/**/PageTree/**
  - tools/e2e-testing/tests/sidebar/page.spec.ts
trash:
  - apps/client-web/**/Trash.*
  - apps/client-web/**/TrashButton/**
  - apps/client-web/**/TrashTable/**
  - apps/client-web/**/TrashPrompt/**
  - tools/e2e-testing/tests/sidebar/trash.spec.ts
topBar:
  - apps/client-web/**/DocumentTopBar/**
  - apps/client-web/**/DocumentContentPage.*
  - apps/client-web/**/CollaboratorsMenu/**
  - apps/client-web/**/PinMenu/**
  - apps/client-web/**/PathBreadcrumb/**
  - tools/e2e-testing/tests/topBar/**
share:
  - apps/client-web/**/ShareMenu/**
  - apps/client-web/**/ShareLinkListItem/**
  - apps/client-web/**/SharePopover/**
discussion:
  - apps/client-web/**/DiscussionMenu/**
history:
  - apps/client-web/**/HistoryMenu/**
  - apps/client-web/**/PageHistoryModal/**
invite:
  - apps/client-web/**/InviteModal/**
space:
  - apps/client-web/common/**
  - apps/client-web/**/SpaceSelect/**
  - apps/client-web/**/settings/**
login:
  - apps/client-web/accounts/**
profile:
  - apps/client-web/**/ProfileModal/**
