apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "brickdoc.fullname" . }}
  labels:
    {{- include "brickdoc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "brickdoc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        mashcard.io/app-engine-build-at: "{{ now | unixEpoch }}"
        {{- include "brickdoc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "brickdoc.serviceAccountName" . }}
      initContainers:
        - name: {{ .Chart.Name }}-db-migrate
          command: ["/app/apps/server-monolith/bin/kube-init"]
          {{- include "brickdoc.deploymentCommon" . }}
          resources:
            {{- if .Values.previewEnv }}
            requests:
              cpu: "0.1"
              memory: 64Mi
            limits:
              cpu: "1.5"
              memory: 512Mi
            {{- else }}
            requests:
              cpu: "1"
              memory: 1024Mi
            {{- end }}
      containers:
        - name: {{ .Chart.Name }}-web
          {{- include "brickdoc.deploymentCommon" . }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 180
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: {{ .Chart.Name }}-sidekiq
          {{- include "brickdoc.deploymentCommon" . }}
          command: ["bundle", "exec", "sidekiq", "-C", "/app/apps/server-monolith/config/sidekiq.yml"]
          resources:
            {{- if .Values.previewEnv }}
            requests:
              cpu: "0.1"
              memory: 64Mi
            limits:
              cpu: "1.5"
              memory: 512Mi
            {{- else }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
