root: true

extends:
  - plugin:@brickdoc/eslint-plugin/react
  - plugin:cypress/recommended

parserOptions:
  project:
    - './tsconfig.json'
    - './packages/*/tsconfig.json'

rules:
  jest/expect-expect: 0
