root: true

extends:
  - plugin:@brickdoc/eslint-plugin/react

parserOptions:
  project:
    - ./tsconfig.json
    - ./tools/*/tsconfig.json
    - ./apps/*/tsconfig.json
    - ./packages/*/tsconfig.json
    - ./gems/plugins/*/tsconfig.json
    - ./spec/dummy/plugins/*/tsconfig.json
    - ./cypress/tsconfig.json
