root: true

extends:
  - plugin:@brickdoc/eslint-plugin/react

parserOptions:
  project:
    - ./tsconfig.json
    - ./packages/*/tsconfig.json
    - ./plugins/*/tsconfig.json
    - ./spec/dummy/plugins/*/tsconfig.json
    - ./cypress/tsconfig.json
