# Lint staged files before committing, see https://github.com/okonet/lint-staged
'*.(ts|tsx|js|jsx)':
  - eslint --cache --fix
  - prettier --write
'*.(json|yml|md|graphql)':
  - prettier --write
'(app|lib|config|gems)/**/*.rb':
  - bundle exec rubocop --parallel --force-exclusion
'*.(css|less)':
  - stylelint --cache --fix
  - prettier --write
