flag_management:
  default_rules:
    carryforward: true
ignore:
  - 'app/**/*'
  - 'lib/**/*'
  - 'db/**/*'
  - 'bin/**/*'
  - 'config/**/*'
  - 'templates/**/*'
  - 'public/**/*'
  - 'gems/**/*'
  - 'e2e-testing/**/*'
  - 'tools/**/*'
  - 'public/**/*'
  - 'packages/brickdoc-design-icons/**/*'
  - 'apps/client-web/BrickdocGraphQL.ts'
  - 'packages/briockdoc-design-system/.storybook'
  - 'packages/brickdoc-design-system/components/*/demos'
  - '**/*.stories.*'
  - '**/spec'
  - '**/dist'
  - '**/__tests__'
  - '**/node_modules'
  - '**/vendor'
