flag_management:
  default_rules:
    carryforward: true
ignore:
  - 'db'
  - 'bin'
  - 'config'
  - 'cypress'
  - 'templates'
  - 'packages/brickdoc-design-icons'
  - 'frontends/BrickdocGraphQL.ts'
  - 'packages/briockdoc-design-system/.storybook'
  - '**/*.stories.*'
  - '**/spec'
  - '**/dist'
  - '**/__tests__'
  - '**/node_modules'
  - '**/vendor'
