flag_management:
  default_rules:
    carryforward: true
ignore:
  - 'app/graphql' # false positive. @see spec/graphql
  - 'app/policies'
  - 'app/jobs'
  - 'app/controllers'
  - 'lib/brick_graphql'
  - 'db'
  - 'bin'
  - 'config'
  - 'templates'
  - 'packages/brickdoc-design-icons'
  - 'apps/client-web/BrickdocGraphQL.ts'
  - 'packages/briockdoc-design-system/.storybook'
  - 'packages/brickdoc-design-system/components/*/demos'
  - '**/*.stories.*'
  - '**/spec'
  - '**/dist'
  - '**/__tests__'
  - '**/node_modules'
  - '**/vendor'
