flag_management:
  default_rules:
    carryforward: true
coverage:
  status:
    # It's noisey to have failed checks on PRs.
    # Because we already have Codecov bot commenting on PRs, here we disable the status check.
    project: off
    patch: off
ignore:
  - 'apps/server-monolith/config/**/*'
  - 'apps/server-monolith/public/**/*'
  - 'e2e-testing/**/*'
  - 'tools/**/*'
  - 'apps/client-web/src/MashcardGraphQL.ts'
  - 'packages/design-icons/**/*'
  - 'packages/schema/**/*'
  - 'packages/design-system/.storybook'
  - 'packages/design-system/components/*/demos'
  - 'plugins/**/*'
  - '**/*.stories.*'
  - '**/spec'
  - '**/dist'
  - '**/__tests__'
  - '**/node_modules'
  - '**/vendor'
  - 'docs/**/*'
  - '**/tmp'
