flag_management:
  default_rules:
    carryforward: true
ignore:
  - 'app/**/*'
  - 'lib/**/*'
  - 'db/**/*'
  - 'bin/**/*'
  - 'config/**/*'
  - 'templates/**/*'
  - 'public/**/*'
  - 'gems/**/*'
  - 'e2e-testing/**/*'
  - 'tools/**/*'
  - 'packages/brickdoc-design-icons/**/*'
  - 'apps/client-web/BrickdocGraphQL.ts'
  - 'apps/server-api/src/cli/**/*'
  - 'apps/server-api/db/**/*'
  - 'packages/briockdoc-design-system/.storybook'
  - 'packages/brickdoc-design-system/components/*/demos'
  - 'packages/dotenv/**/*'
  - 'packages/eslint-plugin-brickdoc/**/*'
  - '**/*.stories.*'
  - '**/spec'
  - '**/dist'
  - '**/__tests__'
  - '**/node_modules'
  - '**/vendor'
  - 'docs/**/*'
  - 'spec/**/*'
  - 'tmp/**/*'
  - 'plugins/gcloud/**/*'
  - 'plugins/sentry/**/*'
