#
# Your Crowdin credentials
#
"project_id" : "439760"
"api_token" : "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJ3UUVxdmhVM3ZMT2EyWGljbVV5VCIsImp0aSI6IjAzZDhkMzBkNGQ2Nzc5YzU0MTA0YTJmZGI1ZjFiY2NiMmI2ZTQ5YjlmMGMzNGY4YWIzODRkZDg1MjFmNDNkMWI5MWU1NTFlYmQ1ZWM4Zjg3IiwiaWF0IjoxNjIzNzQ0MzgzLCJuYmYiOjE2MjM3NDQzODMsImV4cCI6MTYyNjMzNjM4Mywic3ViIjoiMTQ2MDQ0NjgiLCJkb21haW4iOm51bGwsInNjb3BlcyI6WyJwcm9qZWN0Il0sImFzc29jaWF0aW9ucyI6WyIqIl0sInNlc3Npb24iOjB9.ezpX4T3y3DlGOlLehyapIxLGhPug1toCexddDI7LC58wou-8d8h4RG8J1YBdgkgJzK5eSEKNyMhzTK3GrZQuKcomK4HlZnsuov0QWqZnv3-LX-ZWodDQzupRvV2wVJ6Wa72M1KGoZUSkYS69fR9lIi4psgo5LfV7KPmEqV2f5yvKL3VOqRHpwMOov8fq8LA-uz-OwzOOD-PljT7nINZHVNj-W7Hd56zzE5OaFDD79Xa51Kb3yh_K7mzDRyTjXKgEQG_7VPJVt78JN5JgeSuveExEqLMEYTvEvbey9KwFw0HRS274lTcohq4KE8Sn7YDu7MNeSxzMuBoltJ_XVXY5uwzvOo64mw35GHfTsqC-yL47Bkij_3Ky15omImG7P219LXz0Y9c3lqRvON2bew84x7PvlXfr6PDYg6NJdGqxMlGm6tmoftrarEBZqmdwi2tYIZ7MjLN59ZX66Ci6gQ9Ehnzz5qLpwLvVBbqV-o2PzYByIKxr1-Bpc6iQAk-e-S3kLa8GfHnssSoaD_wceBEdWuq0ztV6nILa4B6JN6cj23Prp9joR8xtErGA-arZKhOToDoHNGvxECsJI0OX4I8kE5vqUtmIeElAQoh6wr8tieRbZ4rFB2ImNS-RA4jr8gRdGkbL67GXVyzTj6W0YNUe4iUd4QjpCiKq391cCqBZOB0"
"base_path" : "."
"base_url" : "https://api.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true

#
# Files configuration
#
files: [
 {
  #
  # Source files filter
  # e.g. "/resources/en/*.json"
  #
  "source" : "/config/locales/en-US.yml",

  #
  # Where translations will be placed
  # e.g. "/resources/%two_letters_code%/%original_file_name%"
  #
  "translation" : "/config/locales/%locale%.yml",

  #
  # Files or directories for ignore
  # e.g. ["/**/?.txt", "/**/[0-9].txt", "/**/*\?*.txt"]
  #
  #"ignore" : [],

  #
  # The dest allows you to specify a file name in Crowdin
  # e.g. "/messages.json"
  #
  #"dest" : "",

  #
  # File type
  # e.g. "json"
  #
  #"type" : "",

  #
  # The parameter "update_option" is optional. If it is not set, after the files update the translations for changed strings will be removed. Use to fix typos and for minor changes in the source strings
  # e.g. "update_as_unapproved" or "update_without_changes"
  #
  # "update_option" : "update_without_changes",

  #
  # Start block (for XML only)
  #

  #
  # Defines whether to translate tags attributes.
  # e.g. 0 or 1  (Default is 1)
  #
  # "translate_attributes" : 1,

  #
  # Defines whether to translate texts placed inside the tags.
  # e.g. 0 or 1 (Default is 1)
  #
  # "translate_content" : 1,

  #
  # This is an array of strings, where each item is the XPaths to DOM element that should be imported
  # e.g. ["/content/text", "/content/text[@value]"]
  #
  # "translatable_elements" : [],

  #
  # Defines whether to split long texts into smaller text segments
  # e.g. 0 or 1 (Default is 1)
  #
  # "content_segmentation" : 1,

  #
  # End block (for XML only)
  #

  #
  # Start .properties block
  #

  #
  # Defines whether single quote should be escaped by another single quote or backslash in exported translations
  # e.g. 0 or 1 or 2 or 3 (Default is 3)
  # 0 - do not escape single quote;
  # 1 - escape single quote by another single quote;
  # 2 - escape single quote by backslash;
  # 3 - escape single quote by another single quote only in strings containing variables ( {0} ).
  #
  # "escape_quotes" : 3,

  #
  # Defines whether any special characters (=, :, ! and #) should be escaped by backslash in exported translations.
  # e.g. 0 or 1 (Default is 0)
  # 0 - do not escape special characters
  # 1 - escape special characters by a backslash
  #
  # "escape_special_characters": 0
  #

  #
  # End .properties block
  #

  #
  # Does the first line contain header?
  # e.g. true or false
  #
  #"first_line_contains_header" : true,

  #
  # for spreadsheets
  # e.g. "identifier,source_phrase,context,uk,ru,fr"
  #
  # "scheme" : "",
 }
]
