project_id: '521468'
base_path: apps/server-monolith
base_url: 'https://api.crowdin.com'
preserve_hierarchy: true
files:
  - source: /config/locales/*.en-US.yml
    translation: /config/locales/%file_name%%locale%.yml
    translation_replace:
      en-US: ''
