{{- $fullName := include "brickdoc.fullname" . -}}
apiVersion: apisix.apache.org/v1
kind: ApisixRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "brickdoc.labels" . | nindent 4 }}
spec:
  http:
    {{- if .Values.previewEnv }}
    - name: {{ $fullName }}-mailer
      priority: 2
      match:
        paths:
          - /devtools/mailer*
        hosts:
          - {{ .Values.ingress.host }}
      backends:
        - serviceName: {{ include "brickdoc.devDependenciesService" . }}
          servicePort: 8025
      websocket: true
    {{- end }}          
    - name: {{ $fullName }}
      match:
        paths:
          - /*
        hosts:
          - {{ .Values.ingress.host }}
      backends:
        - serviceName: {{ $fullName }}
          servicePort: 3000
      websocket: true