blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://stackoverflow.com/questions/tagged/brickdoc
    about: Please ask and answer questions here.
  - name: Security Bug
    url: https://github.com/brickdoc/brickdoc/security/policy
    about: Please report security vulnerabilities here.
