default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  username: postgres
  password: <%= ENV['POSTGRES_PASS'] %>

development:
  <<: *default
  database: brickdoc_development



test:
  <<: *default
  database:  brickdoc_test


production:
  <<: *default
  url: <%= ENV['BRICKDOC_DATABASE_URL'] %>
