development:
  secret_key_base: 42ad1f9aa2108a45e6a3369c7382d0bcd301c05185d82314a2916d3d5a2be9fbec963e4f455f94efe7049eb35b04335cd27b67dc4cce03a3d8fe61b135bbc823

test:
  secret_key_base: 42b3ae39b6fb861f30d6cd4733d636ff0506c8b241973e7cd0887a4b25bc6eec88c0711a694ec54c5eb2a506ab339c3347655aceafb5a48eb2b22903d1f960b6

# Ensure that you don't lose it.
# If you change or lose this key you will be unable to access variables stored in database.
# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# Do not keep production secrets in the repository, instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
