# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: frontends
  source_entry_path: entrypoints
  public_root_path: public
  public_output_path: esm-bundle
  cache_path: tmp/cache/webpacker
  webpack_compile_output: true
  compile: false

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  additional_paths: ['packages']

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

development:
  <<: *default

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    client:
      overlay: true
      progress: true
      webSocketURL:
        hostname: localhost
        port: 3035
    https: false
    host: localhost
    port: 3035
    # Hot Module Replacement updates modules while the application is running without a full reload
    hmr: true
    # Inline should be set to true if using HMR; it inserts a script to take care of live reloading
    inline: true
    # Should we use gzip compression?
    compress: true
    # Note that apps that do not check the host are vulnerable to DNS rebinding attacks
    allowed_hosts: 'all'
    # When enabled, nothing except the initial startup information will be written to the console.
    # This also means that errors or warnings from webpack are not visible.
    quiet: false
    pretty: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'

test:
  <<: *default

  # Compile test packs to a separate directory
  public_output_path: packs-test

cicd:
  <<: *default

production:
  <<: *default

  # Cache manifest.json for performance
  cache_manifest: true
