inherit_gem:
  rubocop-brickdoc: rubocop.yml

require:
  - rubocop-graphql
  - rubocop-rails

Rails/DynamicFindBy:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

# TODO: FIXME
GraphQL/ArgumentDescription:
  Enabled: false

GraphQL/ObjectDescription:
  Enabled: false

GraphQL/ExtractInputType:
  Enabled: false

GraphQL/FieldDescription:
  Enabled: false

GraphQL/ExtractType:
  Enabled: false
