# Run `bin/order-podname-blacklist` to optimize blacklist.
---
:common:
  - about
  - accounts
  - admin
  - anonymous
  - anyone
  - api
  - assets
  - auth
  - automation
  - blob
  - dashboard
  - docs
  - features
  - feeds
  - forms
  - graphql
  - history
  - home
  - login
  - logout
  - new
  - plugins
  - public
  - rss
  - search
  - settings
  - sessions
  - setup
  - sign-in
  - sign-up
  - signin
  - signup
  - sitemap
  - uploads
  - user
  - users
  - webhook
  - webhooks
  - workflow
  - apps
  - authorize
  - billing
  - developer
  - devtools
  - feedback
  - git
  - index
  - notifications
  - packages
  - pages
  - password
  - privacy
  - profile
  - reset
  - root
  - spam
  - stafftools
  - www
  - jsonschema
