# Feature Flags (aka Feature Toggles) are a powerful technique, allowing teams to modify system behavior without
# changing code. They fall into various usage categories, and it's important to take that categorization into account
# when implementing and managing toggles. Toggles introduce complexity. We can keep that complexity in check by using
# smart toggle implementation practices and appropriate tools to manage our toggle configuration, but we should also
# aim to constrain the number of toggles in our system.
#
#
# Choose a feature flag type that matches the expected usage:
# `dev` feature flags are short-lived feature flags, used so that unfinished code can be deployed in production.
# `business` feature flags are long-lived feature flags that control operational aspects of MashCard product behavior.

- name: stafftools
  type: dev
