root: true

extends:
  - plugin:@brickdoc/eslint-plugin/react

parserOptions:
  project:
    - ./tsconfig.json

rules:
  'jsx-a11y/no-autofocus': 'off'
overrides:
  - files:
      - '**/*.stories.tsx'
    rules:
      'import/no-default-export': 'off'
      '@typescript-eslint/consistent-type-assertions': 'off'
  - files:
      - '**/stories.test.tsx'
    rules:
      'jest/expect-expect': 'off'
