rules:
  import/no-default-export: off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-floating-promises': off
  max-nested-callbacks:
    - warn
    - 4
  complexity:
    - warn
    - 31
  max-params:
    - warn
    - 8
