{{- if empty .Values.secrets  }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bae-simple-web.fullname" . }}
  labels: {{- include "bae-simple-web.labels" . | nindent 4 }}
type: Opaque
data: 
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote | b64enc }}
{{- end }}
{{- end }}
