{{- if empty .Values.secrets  }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mashcard.fullname" . }}
  labels: {{- include "mashcard.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
