apiVersion: v1
kind: Service
metadata:
  name: {{ include "mashcard.fullname" . }}
  labels: {{- include "mashcard.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3036
      targetPort: 3036
      protocol: TCP
      name: http
  selector: {{- include "mashcard.selectorLabels" . | nindent 4 }}
