root: true

extends:
  - plugin:@brickdoc/eslint-plugin/base

rules:
  jest/no-done-callback: off
  import/no-default-export: off
  jest/no-conditional-expect: off

parserOptions:
  project: ./tsconfig.json
