apiVersion: v1
kind: Service
metadata:
  name: {{ include "mashcard.fullname" . }}
  labels: {{- include "mashcard.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
    - port: 1025
      targetPort: 1025
      protocol: TCP
      name: smtp
    - port: 8025
      targetPort: 8025
      protocol: TCP
      name: mailhog-ui
  selector: {{- include "mashcard.selectorLabels" . | nindent 4 }}
