# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idsteps
---
name: ci
on:
  push:

env:
  POSTGRES_PASS: '123456'
  REDIS_URL: redis://127.0.0.1:6379

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: 'brickdoc_test'
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: '123456'
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Run yarn install
        run: yarn
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Lint the codebase
        run: yarn tsc:check && yarn lint
      - name: Run Jest tests
        run: yarn test:jest --ci --collectCoverage
      - name: Run DB migrations
        run: bundle exec rails db:create db:migrate db:seed
      - name: Start the Rails server
        run: bundle exec rails s -p 3000 &
        env:
          CYPRESS: 1
          RAILS_ENV: development
      - name: Run RSpec tests
        env:
          RAILS_ENV: test
        run: bundle exec rspec --format RspecJunitFormatter --out junit-reports/rspec.xml
      - name: Publish test reports
        if: always()
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: junit-reports/*.xml
      - name: Dump the graphql schema
        run: yarn graphql
      - name: Ensure the server is running
        run: curl http://localhost:3000 -I
      - name: Run Webpacker compilation
        run: bundle exec rails webpacker_compile
      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          config: pageLoadTimeout=10000
      - name: Dump the database schema
        run: bundle exec rails db:schema:dump
        env:
          RAILS_ENV: test
      - name: Add and commit everything
        uses: EndBug/add-and-commit@v7
        if: github.ref != 'refs/heads/master'
        env:
          HUSKY: 0
        with:
          default_author: github_actions
          message: 'ci: bump schemas and dists'
          add: 'app lib packages spec config db frontends'
      - name: Upload build artifacts (when failed)
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          if-no-files-found: ignore
          retention-days: 20
          path: |
            cypress/screenshots/
      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          if-no-files-found: ignore
          retention-days: 20
          path: |
            cypress/videos/
