# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idsteps
---
name: CI
concurrency:
  group: monolith-ci-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    # Make sure same as push
    paths-ignore:
      - .github/**
      - '!.github/workflow/ci.yml'
      - .husky/**
      - packages/eslint-plugin-brickdoc/**
      - gems/rubocop-brickdoc/**
      - 'app/**'
      - 'lib/**'
      - 'spec/**'
      - 'db/**'
      - '**/LICENSE'
      - '**/NOTICE'
      - '**/VERSION'
  push:
    # Make sure same as pull_request
    paths-ignore:
      - .github/**
      - '!.github/workflow/ci.yml'
      - .husky/**
      - packages/eslint-plugin-brickdoc/**
      - gems/rubocop-brickdoc/**
      - 'app/**'
      - 'lib/**'
      - 'spec/**'
      - 'db/**'
      - '**/LICENSE'
      - '**/NOTICE'
      - '**/VERSION'
    branches:
      - master
      - main

env:
  YARN_CHECKSUM_BEHAVIOR: update
  REDIS_URL: redis://localhost:6379
  DATABASE_URL_BASE: postgres://postgres:just4testing@localhost:5432
jobs:
  jest:
    name: Jest Test
    runs-on: ubuntu-latest
    services:
      # image version suggestion same as tools/helm-charts/brickdoc
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: 'brickdoc_next_test'
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'just4testing'
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # To retrieve the preceding commit.
      - name: Get changed ES files
        id: changed-es-files
        uses: tj-actions/changed-files@v19
        with:
          files: |
            yarn.lock
            **/*.ts
            **/*.tsx
            **/*.js
            **/*.jsx
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        if: steps.changed-es-files.outputs.any_changed == 'true'
        with:
          node-version: 18
          cache: yarn
      - name: Run yarn install
        run: yarn install --immutable
        if: steps.changed-es-files.outputs.any_changed == 'true'
      - name: Run Jest tests
        if: steps.changed-es-files.outputs.any_changed == 'true'
        run: yarn test:jest
        env:
          NODE_OPTIONS: '--max-old-space-size=5950'
      - name: Publish Jest test reports
        if: always() && steps.changed-es-files.outputs.any_changed == 'true'
        uses: mikepenz/action-junit-report@v3.0.3
        with:
          report_paths: junit-reports/jest.xml
          check_name: Jest Test Report
      - name: Publish Jest code coverage reports
        if: steps.changed-es-files.outputs.any_changed == 'true'
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: frontend-unit
