# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idsteps
---
name: ci
on:
  push:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: 'brickdoc_test'
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: '123456'
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Yarn install
        run: yarn
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Lint Code
        run: yarn lint
      - name: Run Migrate
        env:
          POSTGRES_PASS: 123456
        run: bundle exec rails db:create db:migrate db:seed
      - name: Run tests
        env:
          CYPRESS: 1
          RAILS_ENV: test
          REDIS_URL: redis://127.0.0.1:6379
          POSTGRES_PASS: 123456
        run: bundle exec rspec && yarn run cypress run
      - name: Dump database schema
        run: bundle exec rails db:schema:dump
        env:
          RAILS_ENV: test
          POSTGRES_PASS: 123456
      - name: Dump graphql schema
        run: yarn graphql
      - name: Add and commit everything
        uses: EndBug/add-and-commit@v7
        if: github.ref != 'refs/heads/master'
        env:
          HUSKY: 0
        with:
          default_author: github_actions
          message: 'ci: bump schema and dists'
          add: 'app lib packages spec config db frontends'
