# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idsteps
---
name: CI
concurrency:
  group: monolith-ci-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    # Make sure same as push
    paths-ignore:
      - .github/**
      - '!.github/workflow/ci.yml'
      - .husky/**
      - packages/eslint-plugin-brickdoc/**
      - gems/rubocop-brickdoc/**
      - '**/LICENSE'
      - '**/NOTICE'
      - '**/VERSION'
  push:
    # Make sure same as pull_request
    paths-ignore:
      - .github/**
      - '!.github/workflow/ci.yml'
      - .husky/**
      - packages/eslint-plugin-brickdoc/**
      - gems/rubocop-brickdoc/**
      - '**/LICENSE'
      - '**/NOTICE'
      - '**/VERSION'
    branches:
      - master
      - main

env:
  YARN_CHECKSUM_BEHAVIOR: update
  POSTGRES_PASS: '123456'
  REDIS_URL: redis://127.0.0.1:6379
  SECURITY_REVERSIBLE_INT_PRIME: 1911469727
  SECURITY_REVERSIBLE_INT_RANDOM: 1996136202
  SECURITY_REVERSIBLE_INT_INVERSE: 2083710303
  UNSPLASH_API_ACCESS_KEY: ${{ secrets.UNSPLASH_API_ACCESS_KEY }}
  UNSPLASH_API_SECRET: ${{ secrets.UNSPLASH_API_SECRET }}
  IFRAMELY_API_ACCESS_KEY: ${{ secrets.IFRAMELY_API_ACCESS_KEY }}
  PDFJS_EXPRESS_LICENSE: ${{ secrets.PDFJS_EXPRESS_LICENSE }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

jobs:
  jest:
    name: Jest Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # To retrieve the preceding commit.
      - name: Get changed ES files
        id: changed-es-files
        uses: tj-actions/changed-files@v18.4
        with:
          files: |
            yarn.lock
            **/*.ts
            **/*.tsx
            **/*.js
            **/*.jsx
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        if: steps.changed-es-files.outputs.any_changed == 'true'
        with:
          node-version: 16
          cache: yarn
      - name: Run yarn install
        run: yarn install --immutable
        if: steps.changed-es-files.outputs.any_changed == 'true'
      - name: Run Jest tests
        if: steps.changed-es-files.outputs.any_changed == 'true'
        run: yarn test:jest
        env:
          NODE_OPTIONS: '--max-old-space-size=5950'
      - name: Publish Jest test reports
        if: always() && steps.changed-es-files.outputs.any_changed == 'true'
        uses: mikepenz/action-junit-report@v3.0.1
        with:
          report_paths: junit-reports/jest.xml
          check_name: Jest Test Report
      - name: Publish Jest code coverage reports
        if: steps.changed-es-files.outputs.any_changed == 'true'
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: frontend-unit
  rspec_and_dump_schema:
    name: Rails RSpec & Schema Dump
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: 'brickdoc_test'
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: '123456'
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # To retrieve the preceding commit.
      - name: Get changed Ruby files
        id: changed-ruby-files
        uses: tj-actions/changed-files@v18.4
        with:
          files: |
            Gemfile.lock
            **/*.rb
            **/*.gemspec
      - name: Install dependencies
        if: steps.changed-ruby-files.outputs.any_changed == 'true'
        run: sudo apt-get update && sudo apt-get install libsodium23 rustc
      - name: Setup Ruby
        if: steps.changed-ruby-files.outputs.any_changed == 'true'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run DB migrations
        if: steps.changed-ruby-files.outputs.any_changed == 'true'
        run: bundle exec rails db:prepare
        env:
          RAILS_ENV: test
      - name: Run RSpec tests
        if: steps.changed-ruby-files.outputs.any_changed == 'true'
        env:
          RAILS_ENV: test
        run: bundle exec rspec --format RspecJunitFormatter --out junit-reports/rspec.xml
      - name: Run RSpec setting tests
        if: steps.changed-ruby-files.outputs.any_changed == 'true'
        env:
          RAILS_ENV: test
        run: cd gems/brickdoc_settings && bundle && bundle exec rspec --format RspecJunitFormatter --out ../../junit-reports/rspec_setting.xml && cd ../..
      - name: Publish RSpec test reports
        if: always() && steps.changed-ruby-files.outputs.any_changed == 'true'
        uses: mikepenz/action-junit-report@v3.0.1
        with:
          report_paths: junit-reports/rspec.xml
          check_name: Rails RSpec Test Report
      - name: Publish RSpec setting test reports
        if: always() && steps.changed-ruby-files.outputs.any_changed == 'true'
        uses: mikepenz/action-junit-report@v3.0.1
        with:
          report_paths: junit-reports/rspec_setting.xml
          check_name: Rails RSpec Test Setting Report
      - name: Get changed database migrations
        id: changed-db-migrations
        uses: tj-actions/changed-files@v18.4
        with:
          files: |
            db\/migrate
      - name: Get changed GraphQL type definitions
        id: changed-gql-typeds
        uses: tj-actions/changed-files@v18.4
        with:
          files: |
            app\/graphql
            lib\/brick_graphql
            graphql.ts$
      - name: Dump the graphql schema
        if: steps.changed-gql-typeds.outputs.any_changed == 'true'
        run: yarn install --immutable && yarn graphql
      - name: Dump the database schema
        if: steps.changed-db-migrations.outputs.any_changed == 'true'
        run: bundle exec rails db:prepare db:schema:dump
      - name: Add and commit everything
        uses: EndBug/add-and-commit@v9
        if: github.ref != 'refs/heads/master'
        env:
          HUSKY: 0
        with:
          default_author: github_actions
          message: 'chore: bump schemas and dists'
          add: 'app lib packages spec config db apps/client-web'
