---
name: Design System Continuous Deployment
on:
  push:
    paths:
      - 'packages/brickdoc-design-system/**'
      - '.github/workflows/design_system_cd.yml'
    branches:
      - master
      - main
permissions:
  id-token: write
  pull-requests: write
  contents: read
  deployments: write
  packages: write
  statuses: write
  actions: write
env:
  YARN_CHECKSUM_BEHAVIOR: update
  GCP_PROJECT: golden-union-341912
jobs:
  cancel:
    # Cancel any previous CI runs to save GH Actions minutes
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  build:
    name: 'Build and Push Docker Image'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: brickdoc-designSystem-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            brickdoc-designSystem-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-buildx-
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./packages/brickdoc-design-system/Dockerfile
          push: true
          tags: ghcr.io/brickdoc/design-system:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    name: 'Deployment to GKE'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3
      - name: GCP Login
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/909250635156/locations/global/workloadIdentityPools/cicd/providers/github-action'
          service_account: 'cicd-bot@${{ env.GCP_PROJECT }}.iam.gserviceaccount.com'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - run: |-
          gcloud --quiet auth configure-docker
      - name: 'Get the GKE cluster Configuration'
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: 'kube-us-central'
          location: 'us-central1'
      - name: 'Deploy to GKE'
        run: |-
          helm upgrade design-system ${{ github.workspace }}/tools/helm-charts/simple-website \
           --install --atomic --timeout 15m --cleanup-on-fail --wait --namespace=corp \
            --set-string image.name=ghcr.io/brickdoc/design-system:latest \
            --set-string ingress.host=design-system.brickdoc.app \
            --set-string envs.BRICKDOC_BUILD=${{ github.sha }} \
