---
name: Design System Continuous Deployment
on:
  push:
    paths:
      - 'packages/brickdoc-design-system/**'
      - '.github/workflows/design_system_cd.yml'
    branches:
      - master
      - main
jobs:
  cancel:
    # Cancel any previous CI runs to save GH Actions minutes
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  build:
    name: 'Build and Push Docker Image'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: brickdoc-designSystem-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            brickdoc-designSystem-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-buildx-
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./packages/brickdoc-design-system/Dockerfile
          push: true
          tags: ghcr.io/brickdoc/design-system:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  deploy:
    name: 'Deployment to BAE'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deployment to App Engine
        uses: brickdoc/app-engine@v1.beta2
        with:
          image: ghcr.io/brickdoc/design-system:latest
          name: design-system
          host: design-system.brickdoc.dev
          extraArgs: '--timeout 10m --cleanup-on-fail'
        env:
          APP_ENV_BRICKDOC_BUILD: ${{ github.sha }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_GLOBAL_CORP_AK }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_GLOBAL_CORP_SECRET }}
