name: Full E2E test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'
env:
  YARN_CHECKSUM_BEHAVIOR: update

jobs:
  playwright:
    name: Playwright Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Run yarn install
        run: yarn install --immutable
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libsodium23 rustc
      - name: Install Playwright
        run: yarn e2e-testing install-deps
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Get E2E account email & password
        id: get_e2e_account
        run: |
          echo ::set-output name=chromium_email::${{ secrets.TRUNK_E2E_LOGIN_EMAIL_1 }}
          echo ::set-output name=chromium_password::${{ secrets.TRUNK_E2E_LOGIN_PASSWORD_1 }}
          echo ::set-output name=firefox_email::${{ secrets.TRUNK_E2E_LOGIN_EMAIL_2 }}
          echo ::set-output name=firefox_password::${{ secrets.TRUNK_E2E_LOGIN_PASSWORD_2 }}
      - name: Run Playwright tests
        run: yarn e2e-testing start
        env:
          NODE_OPTIONS: '--max-old-space-size=5950'
          PLAYWRIGHT_BASE_URL: https://trunk.brickdoc.dev
          E2E_CHROMIUM_LOGIN_EMAIL: ${{ steps.get_e2e_account.outputs.chromium_email }}
          E2E_CHROMIUM_LOGIN_PASSWORD: ${{ steps.get_e2e_account.outputs.chromium_password }}
          E2E_FIREFOX_LOGIN_EMAIL: ${{ steps.get_e2e_account.outputs.firefox_email }}
          E2E_FIREFOX_LOGIN_PASSWORD: ${{ steps.get_e2e_account.outputs.firefox_password }}
      - name: Send Results and Generate Allure Report
        uses: Xotabu4/send-to-allure-server-action@1
        id: allure
        if: ${{ always() }}
        with:
          allure-server-url: https://allure.brickdoc.dev

  slack:
    needs: playwright
    name: Slack
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: |
          echo "::set-output name=uploadedDate::$(TZ=":Asia/Shanghai" date +'%Y-%m-%d %H:%M')"

      - name: Send Slack Message
        uses: archive/github-actions-slack@master
        id: send-message
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: C03D6SMBGTW
          slack-text: Your report is uploaded in ${{needs.playwright.outputs.reportUrl}} at ${{steps.date.outputs.uploadedDate}}, hurry to check it~ 😉
