name: E2E Testing
on: [deployment_status]
concurrency:
  group: monolith-e2e-${{ github.ref }}
  cancel-in-progress: true
env:
  YARN_CHECKSUM_BEHAVIOR: update
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: .github/e2e_rule.yml

  playwright:
    needs: changes
    name: Playwright Test
    if: fromJSON(needs.changes.outputs.apps)[0] != null && github.event.deployment_status.state == 'success' && (github.event.deployment_status.environment == 'pr_preview' || github.event.deployment_status.environment == 'trunk')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Run yarn install
        run: yarn install --immutable
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libsodium23 rustc
      - name: Install Playwright
        run: yarn e2e-testing install-deps
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Get E2E account email & password
        id: get_e2e_account
        run: |
          if [[ $DEPLOY_ENV == 'trunk' ]]; then
              echo ::set-output name=chromium_email::${{ secrets.TRUNK_E2E_LOGIN_EMAIL_1 }}
              echo ::set-output name=chromium_password::${{ secrets.TRUNK_E2E_LOGIN_PASSWORD_1 }}
              echo ::set-output name=firefox_email::${{ secrets.TRUNK_E2E_LOGIN_EMAIL_2 }}
              echo ::set-output name=firefox_password::${{ secrets.TRUNK_E2E_LOGIN_PASSWORD_2 }}
          else
              echo ::set-output name=chromium_email::ADMIN3@brickdoc.com
              echo ::set-output name=chromium_password::PASSWORD3
              echo ::set-output name=firefox_email::ADMIN4@brickdoc.com
              echo ::set-output name=firefox_password::PASSWORD4
          fi
        env:
          DEPLOY_ENV: ${{ github.event.deployment_status.environment }}
      - name: Run Playwright tests
        run: yarn e2e-testing run-playwright ${{ join(fromJSON(needs.changes.outputs.apps), ' ') }}
        if: success()
        env:
          NODE_OPTIONS: '--max-old-space-size=5950'
          PLAYWRIGHT_BASE_URL: ${{ github.event.deployment_status.environment_url }}
          E2E_CHROMIUM_LOGIN_EMAIL: ${{ steps.get_e2e_account.outputs.chromium_email }}
          E2E_CHROMIUM_LOGIN_PASSWORD: ${{ steps.get_e2e_account.outputs.chromium_password }}
          E2E_FIREFOX_LOGIN_EMAIL: ${{ steps.get_e2e_account.outputs.firefox_email }}
          E2E_FIREFOX_LOGIN_PASSWORD: ${{ steps.get_e2e_account.outputs.firefox_password }}
      - name: Upload Playwright screenshots/traces/videos (when failed or flaky)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-test-results
          if-no-files-found: ignore
          retention-days: 3
          path: tools/e2e-testing/test-results/
