name: E2E Testing
on: [deployment_status]
concurrency:
  group: monolith-e2e-${{ github.ref }}
  cancel-in-progress: true
env:
  YARN_CHECKSUM_BEHAVIOR: update
jobs:
  playwright:
    name: Playwright Test
    if: github.event.deployment_status.state == 'success' && (github.event.deployment_status.environment == 'pr_preview' || github.event.deployment_status.environment == 'trunk')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # run 3 copies of the current job in parallel
        shard: [1, 2, 3]
      fail-fast: false
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Run yarn install
        run: yarn install --immutable
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libsodium23 rustc
      - name: Install Playwright
        run: yarn e2e-testing install-deps
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Get E2E account email & password
        id: get_e2e_account
        run: |
          if [$DEPLOY_ENV == 'trunk']
          then
              echo ::set-output name=email::${{ secrets.TRUNK_E2E_LOGIN_EMAIL }}
              echo ::set-output name=password::${{ secrets.TRUNK_E2E_LOGIN_PASSWORD }}
          else
              echo ::set-output name=email::ADMIN3@brickdoc.com
              echo ::set-output name=password::PASSWORD3
          fi
        env:
          DEPLOY_ENV: ${{ github.event.deployment_status.environment }}
      - name: Run Playwright tests
        run: yarn e2e-testing run-playwright --shard=${{ matrix.shard }}/3
        env:
          NODE_OPTIONS: '--max-old-space-size=5950'
          PLAYWRIGHT_BASE_URL: ${{ github.event.deployment_status.environment_url }}
          E2E_LOGIN_EMAIL: ${{ steps.get_e2e_account.outputs.email }}
          E2E_LOGIN_PASSWORD: ${{ steps.get_e2e_account.outputs.password }}
      - name: Fix coverage files
        run: (find e2e-testing/.nyc_output -type f -name "*.json" -print0 | xargs -0 sed -i "s#[\"]/app/#\"$(pwd)/#g") && yarn e2e-testing report
        continue-on-error: true
      - name: Publish Playwright code coverage reports
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: frontend-e2e
      - name: Upload Playwright screenshots/traces/videos (when failed)
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-test-results
          if-no-files-found: ignore
          retention-days: 3
          path: e2e-testing/test-results/
