name: E2E Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

env:
  YARN_CHECKSUM_BEHAVIOR: update

jobs:
  playwright:
    name: Playwright
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        browser: ['chromium', 'firefox']
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Run yarn install
        run: yarn install --immutable
      - name: Install Playwright
        run: yarn e2e-testing install-deps
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        if: steps.changed-ruby-or-rust-files.outputs.any_changed == 'true'
        with:
          toolchain: stable
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: 'apps/server-monolith'
          ruby-version: 3.1.2
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run native build
        run: yarn server build
        if: steps.changed-ruby-or-rust-files.outputs.any_changed == 'true'
      - name: Get E2E account email & password
        id: e2e-account
        run: |
          echo ::set-output name=chromium-email::${{ secrets.TRUNK_E2E_LOGIN_EMAIL_1 }}
          echo ::set-output name=chromium-password::${{ secrets.TRUNK_E2E_LOGIN_PASSWORD_1 }}
          echo ::set-output name=firefox-email::${{ secrets.TRUNK_E2E_LOGIN_EMAIL_2 }}
          echo ::set-output name=firefox-password::${{ secrets.TRUNK_E2E_LOGIN_PASSWORD_2 }}
      - name: Run Playwright tests
        run: yarn e2e-testing run-playwright:${{ matrix.browser }}
        env:
          NODE_OPTIONS: '--max-old-space-size=5950'
          PLAYWRIGHT_BASE_URL: https://trunk.mashcard.dev
          E2E_CHROMIUM_LOGIN_EMAIL: ${{ steps.e2e-account.outputs.chromium-email }}
          E2E_CHROMIUM_LOGIN_PASSWORD: ${{ steps.e2e-account.outputs.chromium-password }}
          E2E_FIREFOX_LOGIN_EMAIL: ${{ steps.e2e-account.outputs.firefox-email }}
          E2E_FIREFOX_LOGIN_PASSWORD: ${{ steps.e2e-account.outputs.firefox-password }}
      - name: Send reports to the allure server
        uses: Xotabu4/send-to-allure-server-action@1
        id: allure
        if: ${{ always() }}
        with:
          allure-server-url: https://allure.brickdoc.dev
          allure-results: tools/e2e-testing/allure-results
      - name: Get current date
        id: date
        if: ${{ always() }}
        run: |
          echo ::set-output name=upload-date::$(TZ=":Asia/Shanghai" date +'%Y-%m-%d %H:%M')
      - name: Send Slack Message
        uses: archive/github-actions-slack@v2.4.0
        if: ${{ always() }}
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: C03D6SMBGTW
          slack-text: Your report is uploaded in ${{ steps.allure.outputs.report-url }} at ${{ steps.date.outputs.upload-date }}, go to check it~ 😉
