name: Full E2E test

on:
  schedule:
    - cron: '0 17 * * *'

env:
  YARN_CHECKSUM_BEHAVIOR: update

jobs:
  playwright:
    name: Playwright Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Run yarn install
        run: yarn install --immutable
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libsodium23 rustc
      - name: Install Playwright
        run: yarn e2e-testing install-deps
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Get E2E account email & password
        id: get_e2e_account
        run: |
          echo ::set-output name=chromium_email::${{ secrets.TRUNK_E2E_LOGIN_EMAIL_1 }}
          echo ::set-output name=chromium_password::${{ secrets.TRUNK_E2E_LOGIN_PASSWORD_1 }}
      - name: Run Playwright tests
        run: yarn e2e-testing run-playwright
        if: success()
        env:
          NODE_OPTIONS: '--max-old-space-size=5950'
          PLAYWRIGHT_BASE_URL: https://trunk.brickdoc.dev
          E2E_CHROMIUM_LOGIN_EMAIL: ${{ steps.get_e2e_account.outputs.chromium_email }}
          E2E_CHROMIUM_LOGIN_PASSWORD: ${{ steps.get_e2e_account.outputs.chromium_password }}
      - name: Upload Playwright screenshots/traces/videos (when failed or flaky)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-test-results
          if-no-files-found: ignore
          retention-days: 3
          path: tools/e2e-testing/test-results/
