name: Linting Code
concurrency:
  group: monolith-linting-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
env:
  # GitHub-hosted runner have 7 gb RAM.
  # 5250mb === 7gb * 0.75
  NODE_OPTIONS: '--max-old-space-size=5950'
jobs:
  es:
    name: ECMAScript
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 # To retrieve the preceding commit.
      - name: Get changed ES files
        id: changed-es-files
        uses: tj-actions/changed-files@v14.6
        with:
          files: |
            yarn.lock
            **/*.ts
            **/*.tsx
            **/*.js
            **/*.jsx
      - name: Setup NodeJS
        if: steps.changed-es-files.outputs.any_changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Run yarn install
        if: steps.changed-es-files.outputs.any_changed == 'true'
        run: yarn install --immutable  --inline-builds
        env:
          CYPRESS_INSTALL_BINARY: '0'
      - name: Run TypeScript checks
        if: steps.changed-es-files.outputs.any_changed == 'true'
        run: yarn tsc:check
      - name: Run ESLint
        if: steps.changed-es-files.outputs.any_changed == 'true'
        run: yarn lint:eslint
