name: Linting Code
concurrency:
  group: monolith-linting-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
  push:
    branches:
      - master
      - main
env:
  YARN_CHECKSUM_BEHAVIOR: update
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: brickdoc
jobs:
  es:
    name: ECMAScript
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      # GitHub-hosted runner have 7 gb RAM.
      # 5250mb === 7gb * 0.75
      NODE_OPTIONS: '--max-old-space-size=5950'
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run yarn install
        run: yarn install --immutable
      - name: Run yarn lint
        run: yarn lint
