name: Deploy Trunk Monolith on BAE
on:
  push:
    paths-ignore:
      - '.husky/**'
      - 'bin/**'
      - 'packages/rubocop-brickdoc/**'
      - 'packages/eslint-plugin-brickdoc/**'
      - '**/*.md'
      - 'packages/**/Dockerfile'
      - '**/.git*'
      - '**/crowdin.yml'
      - '**/LICENSE'
      - '**/NOTICE'
      - '**/VERSION'
    branches:
      - master
      - main
env:
  image: ghcr.io/brickdoc/brickdoc:latest
  domain: trunk.brickdoc.dev
concurrency:
  group: monolith-trunk-cd
jobs:
  build:
    name: 'Build and Push Docker Image'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --immutable
        env:
          CYPRESS_INSTALL_BINARY: '0'
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: brickdocCE-trunk-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            brickdocCE-trunk-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-buildx-
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            "RAILS_ENV=production"
          tags: ${{ env.image }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  deploy:
    name: 'Deployment to BAE'
    environment:
      name: trunk
      url: ${{ env.domain }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3
      - name: Deployment to App Engine
        uses: brickdoc/app-engine@v1.beta3
        with:
          name: brickdoc-ce-trunk
          image: ${{ env.image }}
          host: ${{ env.domain }}
          chart: ${{ github.workspace }}/tools/helm-charts/brickdoc
          extraArgs: '--timeout 10m --cleanup-on-fail'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_GLOBAL_CORP_AK }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_GLOBAL_CORP_SECRET }}
          APP_SECRET_SECRET_KEY_SEED: ${{ secrets.TRUNK_SECRET_KEY_SEED }}
          APP_SECRET_BRICKDOC_DATABASE_URL: ${{ secrets.TRUNK_POSTGRE_URL }}
          APP_SECRET_REDIS_URL: ${{ secrets.TRUNK_REDIS_URL }}
          APP_SECRET_UNSPLASH_API_ACCESS_KEY: ${{ secrets.UNSPLASH_API_ACCESS_KEY }}
          APP_SECRET_UNSPLASH_API_SECRET: ${{ secrets.UNSPLASH_API_SECRET }}
          APP_SECRET_IFRAMELY_API_ACCESS_KEY: ${{ secrets.IFRAMELY_API_ACCESS_KEY }}
          APP_SECRET_PDFJS_EXPRESS_LICENSE: ${{ secrets.PDFJS_EXPRESS_LICENSE }}
          APP_SECRET_SECURITY_REVERSIBLE_INT_INVERSE: ${{ secrets.TRUNK_SECURITY_REVERSIBLE_INT_INVERSE }}
          APP_SECRET_SECURITY_REVERSIBLE_INT_RANDOM: ${{ secrets.TRUNK_SECURITY_REVERSIBLE_INT_RANDOM }}
          APP_SECRET_SECURITY_REVERSIBLE_INT_PRIME: ${{ secrets.TRUNK_SECURITY_REVERSIBLE_INT_PRIME }}
          APP_ENV_SMTP_FROM: brickdoc-ce-trunk@intl-email-service.brickdoc.app
          APP_ENV_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          APP_SECRET_SMTP_URL: ${{ secrets.TRUNK_SMTP_URL }}
          APP_ENV_GITHUB_KEY: 70835aac65b5971f7774
          APP_SECRET_GITHUB_SECRET: ${{ secrets.TRUNK_GITHUB_SECRET }}
          APP_ENV_HOST: ${{ env.domain }}
          APP_ENV_AWS_REGION: us-east-1
          APP_ENV_AWS_PUBLIC_BUCKET: brickdoc-trunk-public
          APP_ENV_AWS_PRIVATE_BUCKET: brickdoc-trunk-private
          APP_ENV_BRICKDOC_BUILD: ${{ github.sha }}.trunk
