name: Destroy PR Preview
concurrency:
  group: pr-preview-env-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    types:
      - closed
permissions:
  id-token: write
  pull-requests: write
  contents: read
  deployments: write
  packages: write
  statuses: write
  actions: write
env:
  GCP_PROJECT: brickdoc-testnet
jobs:
  clean:
    name: Uninstall Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: GCP Login
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/992882677538/locations/global/workloadIdentityPools/cicd/providers/github-action'
          service_account: 'cicd-bot@${{ env.GCP_PROJECT }}.iam.gserviceaccount.com'
      - name: 'Get the GKE cluster Configuration'
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: 'kube-us-dev-clone-1'
          location: 'us-central1'
      - name: 'Remove temp docker image on GitHub packages'
        uses: bots-house/ghcr-delete-image-action@v1.0.1
        continue-on-error: true
        with:
          owner: mashcard
          name: mashcard-snapshot
          token: ${{ secrets.PAT_FOR_PACAKGES }}
          tag: ${{github.event.pull_request.number}}
      - name: Uninstall History Release
        run: |-
          helm uninstall mashcard-pr${{ github.event.pull_request.number }} --namespace=cicd || true
