name: Deploy SaaS Prod Env
concurrency:
  group: sass-prod-deploy
on:
  push:
    tags:
      - 'v**'
permissions:
  id-token: write
  pull-requests: write
  contents: read
  deployments: write
  packages: write
  statuses: write
  actions: write
env:
  YARN_CHECKSUM_BEHAVIOR: update
  image: ghcr.io/brickdoc/brickdoc-saas
  domain: brickdoc.com
  GCP_PROJECT: golden-union-341912
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_ORG: brickdoc-inc
  SENTRY_PROJECT: brickdoc-saas-prod
jobs:
  build:
    name: 'Build and Push Docker Image'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: sentry-cli releases new brickdoc@${{ steps.get_version.outputs.VERSION }} && sentry-cli releases set-commits brickdoc@${{ steps.get_version.outputs.VERSION }} --auto --ignore-missing
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: |
            RAILS_ENV=production
            VERSION=${{ steps.get_version.outputs.VERSION }}
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
            SENTRY_ORG=${{ env.SENTRY_ORG }}
            SENTRY_PROJECT=${{ env.SENTRY_PROJECT }}
          tags: ${{ env.image }}:v${{ steps.get_version.outputs.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    name: 'Deployment to GKE'
    environment:
      name: production
      url: https://${{ env.domain }}/
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
      - name: Get the start time
        id: get_start_time
        run: echo ::set-output name=START_TIME::$(date +%s)
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm install -g @sentry/cli
      - name: GCP Login
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/909250635156/locations/global/workloadIdentityPools/cicd/providers/github-action'
          service_account: 'cicd-bot@${{ env.GCP_PROJECT }}.iam.gserviceaccount.com'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - run: |-
          gcloud --quiet auth configure-docker
      - name: 'Get the GKE cluster Configuration'
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: 'kube-us-central'
          location: 'us-central1'
      - name: 'Deploy to GKE'
        run: |-
          helm upgrade brickdoc-prod ${{ github.workspace }}/tools/helm-charts/brickdoc \
           --install --atomic --timeout 15m --cleanup-on-fail --wait --namespace=saas \
            --set-string image.name=${{ env.image }}:v${{ steps.get_version.outputs.VERSION }} \
            --set-string ingress.host=${{ env.domain }} \
            --set serviceAccount.create=false \
            --set-string serviceAccount.name=saas-main-app \
            --set-string resources.requests.cpu=1 \
            --set-string resources.requests.memory=1024Mi \
            --set-string envs.SMTP_FROM=saas-no-reply@push-service.brickdoc.com \
            --set-string envs.SENTRY_DSN=https://f44be883f4d7479bb089213767508c1a@o1150336.ingest.sentry.io/6223078 \
            --set-string envs.HOST=${{ env.domain }} \
            --set-string envs.ASSET_HOST=https://s3.brickapis.com/globalcdn/brickdoc-saas-prod \
            --set-string envs.BRICKDOC_BUILD=${{ github.sha }}.saas-prod \
            --set-string envs.GOOGLE_CLOUD_PROJECT=${{ env.GCP_PROJECT }} \
            --set-string envs.GCP_KMS_FRN=projects/${{ env.GCP_PROJECT }}/locations/global/keyRings/global-saas/cryptoKeys/sass-master-key \
            --set-string envs.GCS_PRIVATE_BUCKET=pvt.us-edge.brickdocusercontent.com \
            --set-string envs.GCS_PUBLIC_BUCKET=pub.us-edge.brickdocusercontent.com \
            --set-string secrets.SECRET_KEY_SEED=${{ secrets.SAAS_PROD_SECRET_KEY_SEED }} \
            --set-string secrets.BRICKDOC_DATABASE_URL=${{ secrets.SAAS_PROD_POSTGRE_URL }} \
            --set-string secrets.REDIS_URL=${{ secrets.SAAS_PROD_REDIS_URL }} \
            --set-string secrets.UNSPLASH_API_ACCESS_KEY=${{ secrets.UNSPLASH_API_ACCESS_KEY }} \
            --set-string secrets.UNSPLASH_API_SECRET=${{ secrets.UNSPLASH_API_SECRET }} \
            --set-string secrets.IFRAMELY_API_ACCESS_KEY=${{ secrets.SAAS_PROD_IFRAMELY_API_ACCESS_KEY }} \
            --set-string secrets.SECURITY_REVERSIBLE_INT_INVERSE=${{ secrets.SAAS_PROD_SECURITY_REVERSIBLE_INT_INVERSE }} \
            --set-string secrets.SECURITY_REVERSIBLE_INT_RANDOM=${{ secrets.SAAS_PROD_SECURITY_REVERSIBLE_INT_RANDOM }} \
            --set-string secrets.SECURITY_REVERSIBLE_INT_PRIME=${{ secrets.SAAS_PROD_SECURITY_REVERSIBLE_INT_PRIME }} \
            --set-string secrets.SMTP_URL=${{ secrets.SAAS_PROD_SMTP_URL }} \
            --set-string secrets.GOOGLE_OAUTH2_ID=${{ secrets.SAAS_PROD_GOOGLE_OAUTH2_ID }} \
            --set-string secrets.GOOGLE_OAUTH2_SECRET=${{ secrets.SAAS_PROD_GOOGLE_OAUTH2_SECRET }}
      - run: sentry-cli releases deploys brickdoc@${{ steps.get_version.outputs.VERSION }} new -e production -t $(($(date +%s)-${{ steps.get_start_time.outputs.START_TIME }}))
