# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark Stale Issues and PRs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '30 0 * * *'

jobs:
  stale:
    name: Find and Mark
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-label: 'no-pr-activity'
          stale-pr-message: >
            This pull request has been automatically marked as stale because it has not had
            recent activity. It will be closed in 5 days if no further activity occurs. Thank you
            for your contributions.
          days-before-pr-stale: 45
          days-before-pr-close: 5
          stale-issue-label: 'no-issue-activity'
          days-before-issue-stale: 30
          days-before-issue-close: 7
          stale-issue-message: >
            This issue has been automatically marked as stale because it has been open for 30 days
            with no response from the author. It will be closed in next 7 days if no further
            activity occurs from the issue author.
          close-issue-message: >
            This issue has been closed because it has not received response from the issue author.
