name: Unit Test
concurrency:
  group: monolith-ci-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
  push:
    branches:
      - master
      - main
env:
  YARN_CHECKSUM_BEHAVIOR: update
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: brickdoc
  REDIS_URL: redis://localhost:6379
  DATABASE_URL_BASE: postgres://postgres:just4testing@localhost:5432
jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    timeout-minutes: 20
    services:
      # image version suggestion same as tools/helm-charts/brickdoc
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: 'brickdoc_next_test'
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'just4testing'
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run yarn install
        run: yarn install --immutable
      - name: Build Rust deps
        run: yarn build:rust
      - name: Run Jest tests
        run: yarn test:jest
        env:
          NODE_OPTIONS: '--max-old-space-size=5950'
      - name: Publish Jest test reports
        if: always()
        uses: mikepenz/action-junit-report@v3.0.3
        with:
          report_paths: '**/junit-reports/jest.xml'
          check_name: Jest Test Report
      - name: Publish Jest code coverage reports
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: frontend-unit
