name: Unit Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '.husky/**'
      - '**.md'
      - '**/LICENSE'
      - '.github/**'
      - '!.github/workflows/unit_test.yml'
      - 'tools/e2e-testing/**'

env:
  NODE_OPTIONS: '--max-old-space-size=5950'
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: brickdoc
  REDIS_URL: redis://localhost:6379
  MASHCARD_DATABASE_URL: postgres://postgres:just4testing@localhost:5432
  MASHCARD_CLOUD_LICENSE: 'I hereby swear that I have obtained written permission from the Brickdoc Inc of this plugin to use it.'
  SYSINFO: GITHUB_CI

jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Run yarn install
        run: yarn install --immutable
      - name: Run Jest tests
        run: yarn turbo run test:jest
      - name: Publish Jest code coverage reports
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: frontend-unit
          fail_ci_if_error: true
          verbose: true

  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    services:
      # image version suggestion same as tools/helm-charts/mashcard
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: 'mashcard_test'
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'just4testing'
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # Retrieve the preceding commit to calculate changed files
      - name: Get changed ruby/rust files
        id: changed-ruby-or-rust-files
        uses: tj-actions/changed-files@v29.0.3
        with:
          files: |
            **/*.rb
            **/*.rs
            **/Gemfile
            **/Gemfile.lock
            **/Cargo.toml
            **/Cargo.lock
      - name: Get changed database migrations
        id: changed-db-migrations
        uses: tj-actions/changed-files@v29.0.3
        with:
          files: |
            apps/server-monolith/db/migrate
      - name: Get changed GraphQL type definitions (ruby)
        id: changed-gql-typeds-ruby
        uses: tj-actions/changed-files@v29.0.3
        with:
          files: |
            apps/server-monolith/app/graphql
      - name: Get changed GraphQL type definitions (ts)
        id: changed-gql-typeds-ts
        uses: tj-actions/changed-files@v29.0.3
        with:
          files: |
            **/graphql.ts
      - name: Install Dependencies
        if: steps.changed-ruby-or-rust-files.outputs.any_changed == 'true'
        run: sudo apt-get update && sudo apt-get install libsodium23
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        if: steps.changed-ruby-or-rust-files.outputs.any_changed == 'true'
        with:
          toolchain: stable
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        if: steps.changed-ruby-or-rust-files.outputs.any_changed == 'true'
        with:
          ruby-version: 3.1.2
          working-directory: 'apps/server-monolith'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        if: steps.changed-ruby-or-rust-files.outputs.any_changed == 'true' || steps.changed-gql-typeds-ts.outputs.any_changed == 'true'
        with:
          node-version: 18
          cache: yarn
      - name: Run yarn install
        if: steps.changed-ruby-or-rust-files.outputs.any_changed == 'true' || steps.changed-gql-typeds-ts.outputs.any_changed == 'true'
        run: yarn install --immutable && yarn husky install
      - name: Build native ext
        if: steps.changed-ruby-or-rust-files.outputs.any_changed == 'true'
        run: yarn turbo run rust:build
      - name: Run DB migrations
        if: steps.changed-ruby-or-rust-files.outputs.any_changed == 'true'
        run: yarn server bundle exec rails db:prepare
        env:
          RAILS_ENV: test
      - name: Run RSpec tests
        if: steps.changed-ruby-or-rust-files.outputs.any_changed == 'true'
        env:
          RAILS_ENV: test
        run: yarn turbo run test:rspec
      - name: Publish RSpec code coverage reports
        if: steps.changed-ruby-or-rust-files.outputs.any_changed == 'true'
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: backend-unit
          fail_ci_if_error: true
          verbose: true
      - name: Dump the database schema
        if: github.event_name == 'pull_request' && steps.changed-db-migrations.outputs.any_changed == 'true'
        run: yarn server dump:db
      - name: Dump the graphql schema
        if: github.event_name == 'pull_request' && steps.changed-gql-typeds-ruby.outputs.any_changed == 'true'
        run: yarn server dump:graphql
      - name: Run graphql-codegen
        if: github.event_name == 'pull_request' && (steps.changed-gql-typeds-ruby.outputs.any_changed == 'true' || steps.changed-gql-typeds-ts.outputs.any_changed == 'true')
        run: yarn web generate:graphql
      - name: Get all changed files to commit
        id: get_files_to_commit
        if: github.event_name == 'pull_request'
        run: echo ::set-output name=files::$({ git ls-files --modified && git ls-files -o --exclude-standard; } | awk '{print "./**/" $0}')

      - name: Upload generated schemas
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: schemas
          path: ${{ steps.get_files_to_commit.outputs.files }}
          retention-days: 1

  commit:
    name: Dump Schemas
    needs: rspec
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
        with:
          # https://github.com/EndBug/add-and-commit#working-with-prs
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.PAT_FOR_BOT_CREATED_PR }}
      - name: Download generated schemas
        uses: actions/download-artifact@v3
        continue-on-error: true
        with:
          name: schemas
      - name: Add and commit everything
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'chore: bump schemas and dists'
